name: yalla_ya_dawry
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  google_fonts: ^0.2.0

  http: ^0.12.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Almarai
      fonts:
        - asset: fonts/Almarai-Bold.ttf
        - asset: fonts/Almarai-ExtraBold.ttf
        - asset: fonts/Almarai-Light.ttf
        - asset: fonts/Almarai-Regular.ttf



